FROM node:20-alpine AS builder

# Définit le dossier de travail
WORKDIR /app

# Copie les fichiers nécessaires
COPY package.json package-lock.json ./

# Installe les dépendances
RUN npm install

# Copie le reste des fichiers
COPY . .

# Build l'application
RUN npm run build

# Étape finale : Serveur Nginx
FROM nginx:alpine

# Copie les fichiers buildés dans le dossier Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Copie la configuration Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose le port
EXPOSE 8081

# Commande de démarrage
CMD ["nginx", "-g", "daemon off;"]