apiVersion: v1
kind: Namespace
metadata:
  name: chatbootfsts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: chatbootfsts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: "fsts_chatboot"
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: chatbootfsts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
        - name: ndots
          value: "2"
        - name: edns0
      containers:
      - name: backend
        image: walidhbabou/chatbootfsts-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/fsts_chatboot"
        - name: JWT_SECRET_KEY
          value: "39NtsAHJrQh0fdR2YoqU+dX1oJWly2Vsm/yHdnOQ19Q="
        - name: RASA_API_URL
          value: "http://rasa:5005"  # URL de Rasa
        - name: FLASK_ENV
          value: "production"
        - name: FLASK_HOST  
          value: "0.0.0.0"
        - name: FLASK_PORT
          value: "5000"
        - name: CORS_ORIGINS
          value: "*"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: chatbootfsts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: walidhbabou/chatbootfsts-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: VITE_API_URL
          value: "http://52.54.79.139:30090/api"  # URL du backend
        - name: VITE_RASA_URL
          value: "http://rasa:5005"  # URL de Rasa
        - name: NODE_ENV
          value: "production"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa
  namespace: chatbootfsts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa
  template:
    metadata:
      labels:
        app: rasa
    spec:
      containers:
      - name: rasa
        image: walidhbabou/chatbootfsts-rasa:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5005
        env:
        - name: SANIC_HOST
          value: "0.0.0.0"
        - name: SANIC_PORT
          value: "5005"
        command: ["rasa", "run", "--enable-api", "--cors", "*", "--debug"]
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
---
# Service MongoDB
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: chatbootfsts
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: chatbootfsts
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30090
---
# Service Frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: chatbootfsts
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30089
---
# Rasa Service
apiVersion: v1
kind: Service
metadata:
  name: rasa
  namespace: chatbootfsts
spec:
  type: NodePort
  selector:
    app: rasa
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
      nodePort: 30091