FROM python:3.12-slim

# Définit le dossier de travail
WORKDIR /app

# Copie les fichiers de dépendances
COPY requirements.txt .

# Installe les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Copie le reste des fichiers
COPY . .

# Définit les variables d'environnement
ENV FLASK_APP=run.py
ENV FLASK_ENV=production

# Expose le port de l'application
EXPOSE 5000

# Commande de démarrage
CMD ["python", "run.py"]